export const GET_TOKEN = 'GET_TOKEN';
export const FETCH_TOKEN_SUCESS = 'FETCH_TOKEN_SUCESS';
export const FETCH_TOKEN_FAILED = 'FETCH_TOKEN_FAILED';

export const FETCH_MENU = 'FETCH_MENU';
export const FETCH_MENU_SUCCESS = 'FETCH_MENU_SUCCESS';
export const FETCH_MENU_FAILED = 'FETCH_MENU_FAILED';

export const FETCH_CURRENCY_RATE = 'FETCH_CURRENCY_RATE';
export const FETCH_CURRENCY_RATE_SUCCESS = 'FETCH_CURRENCY_RATE_SUCCESS';
export const FETCH_CURRENCY_RATE_FAILED = 'FETCH_CURRENCY_RATE_FAILED';

export const FETCH_ASSET = 'FETCH_ASSET';
export const FETCH_ASSET_SUCCESS = 'FETCH_ASSET_SUCCESS';
export const FETCH_ASSET_FAILED = 'FETCH_ASSET_FAILED';

export const FETCH_TRADING_ACC = 'FETCH_TRADING_ACC';
export const FETCH_TRADING_ACC_SUCCESS = 'FETCH_TRADING_ACC_SUCCESS';
export const FETCH_TRADING_ACC_FAILED = 'FETCH_TRADING_ACC_FAILED';

export const FETCH_TYPE_ORDER = 'FETCH_TYPE_ORDER';
export const FETCH_TYPE_ORDER_SUCCESS = 'FETCH_TYPE_ORDER_SUCCESS';
export const FETCH_TYPE_ORDER_FAILED = 'FETCH_TYPE_ORDER_FAILED';

export const FETCH_STATUS_ORDER = 'FETCH_STATUS_ORDER';
export const FETCH_STATUS_ORDER_SUCCESS = 'FETCH_STATUS_ORDER_SUCCESS';
export const FETCH_STATUS_ORDER_FAILED = 'FETCH_STATUS_ORDER_FAILED';

export const FETCH_TRADER = 'FETCH_TRADER';
export const RESET_TRADER = 'RESET_TRADER';
export const FETCH_TRADER_SUCCESS = 'FETCH_TRADER_SUCCESS';
export const FETCH_TRADER_FAILED = 'FETCH_TRADER_FAILED';
export const UPDATE_TRADER_SUCCESS = 'UPDATE_TRADER_SUCCESS';
export const UPDATE_TRADER_FAILED = 'UPDATE_TRADER_FAILED';
export const FETCH_TRADER_BY_TRADING_ACC_SUCCESS = 'FETCH_TRADER_BY_TRADING_ACC_SUCCESS';
export const FETCH_TRADER_BY_TRADING_ACC_FAILED = 'FETCH_TRADER_BY_TRADING_ACC_FAILED';

export const FETCH_STAFF = 'FETCH_STAFF';
export const RESET_STAFF = 'RESET_STAFF';
export const FETCH_STAFF_SUCCESS = 'FETCH_STAFF_SUCCESS';
export const FETCH_STAFF_FAILED = 'FETCH_STAFF_FAILED';

export const FETCH_OFFER_EXCHANGE = 'FETCH_OFFER_EXCHANGE';
export const FETCH_OFFER_EXCHANGE_SUCCESS = 'FETCH_OFFER_EXCHANGE_SUCCESS';
export const FETCH_OFFER_EXCHANGE_FAILED = 'FETCH_OFFER_EXCHANGE_FAILED';

export const POST_OFFER_EXCHANGE = 'POST_OFFER_EXCHANGE';
export const POST_OFFER_EXCHANGE_SUCCESS = 'POST_OFFER_EXCHANGE_SUCCESS';
export const POST_OFFER_EXCHANGE_FAILED = 'POST_OFFER_EXCHANGE_FAILED';

export const FETCH_USER_GROUP = 'FETCH_USER_GROUP';
export const FETCH_USER_GROUP_SUCCESS = 'FETCH_USER_GROUP_SUCCESS';
export const FETCH_USER_GROUP_FAILED = 'FETCH_USER_GROUP_FAILED';

export const UPDATE_USER_GROUP_SUCCESS = 'UPDATE_USER_GROUP_SUCCESS';
export const UPDATE_USER_GROUP_FAILED = 'UPDATE_USER_GROUP_FAILED';

export const FETCH_ROLE_CLAIM = 'FETCH_ROLE_CLAIM';
export const FETCH_ROLE_CLAIM_SUCCESS = 'FETCH_ROLE_CLAIM_SUCCESS';
export const FETCH_ROLE_CLAIM_FAILED = 'FETCH_ROLE_CLAIM_FAILED';

export const UPDATE_ROLE_CLAIM = 'UPDATE_ROLE_CLAIM';
export const UPDATE_ROLE_CLAIM_SUCCESS = 'UPDATE_ROLE_CLAIM_SUCCESS';
export const UPDATE_ROLE_CLAIM_FAILED = 'UPDATE_ROLE_CLAIM_FAILED';

export const DEPOSIT_SUCCESS = 'DEPOSIT_SUCCESS';
export const DEPOSIT_FAILED = 'DEPOSIT_FAILED';

export const WITHDRAWAL_SUCCESS = 'WITHDRAWAL_SUCCESS';
export const WITHDRAWAL_FAILED = 'WITHDRAWAL_FAILED';

export const FETCH_OFFER_HISTORY_SUCCESS = 'FETCH_OFFER_HISTORY_SUCCESS';
export const FETCH_OFFER_HISTORY_FAILED = 'FETCH_OFFER_HISTORY_FAILED';

export const FETCH_TRADING_ACC_HISTORY_SUCCESS = 'FETCH_TRADING_ACC_HISTORY_SUCCESS';
export const FETCH_TRADING_ACC_HISTORY_FAILED = 'FETCH_TRADING_ACC_HISTORY_FAILED';

export const FETCH_REVENUE_SUCCESS = 'FETCH_REVENUE_SUCCESS';
export const FETCH_REVENUE_FAILED = 'FETCH_REVENUE_FAILED';